# Generated by Django 3.1 on 2020-08-05 13:42

import cources.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=cources.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=cources.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
